job_name: "test_temp_fact_mm_transaction_read"
description: "Test job to read from the temp_fact_mm_transaction_source and display a few rows."

input_source:
  name: "temp_fact_mm_transaction_source"
  version: "v1"
  # No load_params needed for a simple read test

feature_transformers: [] # No transformations needed for this test

output_sink:
  sink_type: "display"
  config:
    num_rows: 10
    truncate: false
