job_name: "generate_transaction_features"
description: "Generates a set of derived features from the fact_mm_transactions data."
input_source:
  name: "temp_fact_mm_transaction_source"
  version: "v1"
feature_transformers:
  - name: "TransactionIndicatorDeriver"
    params: {}
  - name: "TransactionDatetimeDeriver"
    params: {}
  - name: "TransactionStatusDeriver"
    params: {}
  - name: "TransactionChannelDeriver"
    params: {}
  - name: "TransactionValueDeriver"
    params:
      high_value_threshold: 1000.0
      input_col: "transactionamount"
      output_col: "is_high_value_transaction"
  - name: "TransactionModeDeriver"
    params: {}
  - name: "TransactionCategoryDeriver"
    params: {}
output_sink:
  sink_type: "delta_table"
  config:
    path: "temp.feature_platform_testing.temp_transaction_features_v1"
    mode: "overwrite"
    options:
      mergeSchema: "true"
    # description was not in OutputSinkParams, removing for now. Add if model supports it.
    # description: "Features generated from temp_fact_mm_transaction table."
